include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unused_local_variable: ignore
    unused_element: ignore
    no_leading_underscores_for_local_identifiers: ignore
    non_constant_identifier_names: ignore
    strict_top_level_inference: ignore
    use_super_parameters: ignore
    unused_element_parameter: ignore